sudo: false
language: python

os:
 - linux

python:
  - "3.6"

global:
  env:
    - COMMIT_AUTHOR_EMAIL: "f.zapata@esciencecenter.nl"

install:
  - (git clone git://github.com/MD-Studio/MDStudio.git --branch v1 --single-branch && pip install -e MDStudio/mdstudio)
  # install library
  - pip install .[test]

script:
  - (cd tests && coverage run -m unittest discover -vvv)
  
branches:
  only:
    - master
